### ISSUE TITLE
F4 maturity indicator - manual search does not result in a hit

### ISSUE THREAD

**Issue by jormercury** [NanoCommons/wgf-fairdata-analysis#6]
**_Issue_**: when inserting the titles as reported in the jupyter notebooks no hit is found in google dataset search, although the output indicates a score of 1.

This was tested for
[**FAIR_assessment_eNanoMapper.ipynb**](https://github.com/NanoCommons/wgf-fairdata-analysis/blob/master/FAIR_assessment_eNanoMapper.ipynb)
Dataset titles: 
titanium_dioxide: TiO2 NP (Dopamine covered Fe3O4@TiO2)
--> F4: [1]
https://datasetsearch.research.google.com/search?query=TiO2%20NP%20(Dopamine%20covered%20Fe3O4%40TiO2)

[**FAIR_assessment_cnanolab.ipynb.**](https://github.com/NanoCommons/wgf-fairdata-analysis/blob/master/FAIR_assessment_cnanolab.ipynb)
Dataset titles: 
titanium_dioxide: NUS_NUHS-FPengNatNano2019-01
--> F4: [1]
result: https://datasetsearch.research.google.com/search?query=NUS_NUHS-FPengNatNano2019-01

**_Problem_**: this would mean F4 should be scored 0, currently the notebooks output 1.

**_note_**: Although the specific dataset seems not available in googde dataset search, the eNanomapper repositorie is: https://datasetsearch.research.google.com/search?query=NANoREG%20-%20eNanoMapper%20database&docid=lxtA2w6HUMvMfVDcAAAAAA%3D%3D

**Comment by egonw** [comment]
@ammar257ammar, can you please have a look at this?

**Comment by ammar257ammar** [comment]
Dear @jormercury,

Actually, the F4 principle here is assessed for the database itself (in this case eNanoMapper/caNanoLab) and not for the nano materials inside them, since those are not datasets but entries in the assessed databases. 
Also, it is important to notice that the principle F4 is assessed manually and its value is filled manually also in the Jupyter notebook (as described in the paper (https://doi.org/10.3390/nano10102068), and this applies also the the principle I1. Hence, if a hit in Google Dataset is found for eNanoMapper for example, then the principle F4 value is manually assigned to one in the code "F4.append(1)", other wise it will be zero "F4.append(0)". 

But I notice the source of confusion here, because the code prints:
"Dataset titles:
titanium_dioxide: NUS_NUHS-FPengNatNano2019-01"

This should be "Use case title" and not "Dataset title", so like this:
"Use case title:
titanium_dioxide: NUS_NUHS-FPengNatNano2019-01"

We should fix the printed text for those notebooks, but that does not affect the result because anyway the F4 value is set manually.

Thank you for your feedback.

Please let us know if you have other questions/comments.

I will close this issue now.

**Comment by jormercury** [comment]
Dear @ammar257ammar. The first part of your comment is clear. For F4 the search terms should be the database title hosting the dataset. Indeed the two database titles are found in google dataset search.
But in the paper it states for F4 in table 2: "Dataset title found in Google Dataset Search (data and metadata) (M)". This still remains confusing, specificaly when the code prints something which is apparently not used in the metric for F4. I understood this differntly to how you applied it. In the paper it states F4 is related to metadata and data, which to me is what the combination of the use case title and database title are. It would be good to specify exactly how this is or should be implemented here.

So two suggestions. 
1. A change of the code to print the text to be searched, so indeed the database?/data repository? title instead of the use case title. To me adding use case title would cause more confusion and break the link with terminology applied in the paper.
2. Add some explenation and clarification on the terminlogy. What is meant by the term Dataset title in the paper and here. Some additional documentation or user guide will benefit use of these metrics. If needed update the terminology.

What do you think? (@egonw , @ammar257ammar )

**Comment by ammar257ammar** [comment]
Dear @jormercury,

You have a valid point here. I agree with you suggestions.

The first suggestion goes more in-line with having a clear understandable printed text that reflect the implied implementation.

I updated all the four notebooks in this repository to print the database/repository title (title to be searched on Google Dataset).

You feedback is much appreciated.

Please let me know if you have any other questions/suggestions.

Sincerely,
Ammar
